In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a1 = a.reshape(3, 4)
a2 = a.reshape(4, 3)
a3 = a.reshape(2, 6)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [4]:
a1 = a.reshape(3, -1)
a2 = a.reshape(4, -1)
a3 = a.reshape(2, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [5]:
print("Массив не одномерный, его размерность:", a5.reshape(-1, 1).ndim)

Массив не одномерный, его размерность: 2


In [6]:
b = np.random.randn(3, 4)
b, b.size

(array([[-0.96566862, -1.90599138, -2.10335712, -0.20843975],
        [ 0.3560042 ,  0.86186614,  0.5108974 ,  0.29325896],
        [ 1.9482749 ,  1.32066032,  1.5027229 ,  0.07175351]]),
 12)

In [7]:
b1 = b.flatten()
b1, b1.size, b1.ndim

(array([-0.96566862, -1.90599138, -2.10335712, -0.20843975,  0.3560042 ,
         0.86186614,  0.5108974 ,  0.29325896,  1.9482749 ,  1.32066032,
         1.5027229 ,  0.07175351]),
 12,
 1)

In [8]:
a = np.arange(20, 0, -2)
b = np.arange(20, 1, -2)
b.resize(1, 10)
print(f"{a}, {b} \nРазмерность массивов: {a.ndim}, {b.ndim}")

[20 18 16 14 12 10  8  6  4  2], [[20 18 16 14 12 10  8  6  4  2]] 
Размерность массивов: 1, 2


In [9]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
a, b, v, v.size

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

In [10]:
a = np.arange(0, 12, 1)
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [12]:
B = A.dot(At)
print(f"{B}\nРазмер матрицы B: {B.size}\nНевозможно посчитать обратную матрицу, так как определитель матрицы B = {np.linalg.det(B)}")

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы B: 16
Невозможно посчитать обратную матрицу, так как определитель матрицы B = 0.0


In [13]:
np.random.seed(42)
print(np.random.random())
np.random.seed(42)
print(np.random.random())

0.3745401188473625
0.3745401188473625


In [14]:
c = np.random.randint(0, 16, 16)
c

array([12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7])

In [15]:
C = np.reshape(c, (4, 4))
C

array([[12, 14, 10,  7],
       [12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7]])

In [16]:
D = C * 10 + B
D

array([[125, 154, 123, 102],
       [134,  90, 146, 212],
       [ 43, 146, 249, 312],
       [102, 162, 242, 372]])

In [17]:
D_inv = np.linalg.inv(D)
print(f"Определитель: {np.linalg.det(D)}\nРанг: {np.linalg.matrix_rank(D)}\n{D_inv}")

Определитель: -149097600.0
Ранг: 4
[[ 0.0004711   0.0111539  -0.00253901 -0.00435621]
 [ 0.00957225 -0.01715762 -0.00876527  0.01450486]
 [-0.00167085  0.01408514  0.02130578 -0.02543824]
 [-0.00321078 -0.00474937 -0.0093469   0.01411451]]


In [18]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
E = np.where(D_inv, B, C)
E, B, C

(array([[  5,  14,  10,   7],
        [ 14,   4,   6, 122],
        [  2,  86, 149,  10],
        [  7,   4,   3, 302]]),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[12, 14, 10,  7],
        [12,  4,  6,  9],
        [ 2,  6, 10, 10],
        [ 7,  4,  3,  7]]))